name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install Flask pytest pytest-cov

      - name: Run tests
        run: |
          pytest --cov=app --cov-report=xml
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  vulnerability_scan:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t flask-app:latest .

      - name: Install Trivy
        run: |
          mkdir -p $HOME/.trivy
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b $HOME/.trivy
  
      - name: Scan for vulnerabilities
        run: |
          $HOME/.trivy/trivy image --severity HIGH,CRITICAL flask-app:latest

  sonar_scan:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

    #   - name: SonarCloud Scan
    #     uses: SonarSource/sonarcloud-github-action@master
    #     env:
    #       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  docker_publish:
    runs-on: ubuntu-latest
    needs: [vulnerability_scan, sonar_scan]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Build Docker Image
        run: |
            docker build -t flask-app:latest .
      - name: Login to Docker Hub
        run: |
            echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Push Docker Image
        run: |
            docker tag flask-app:latest ${{ secrets.DOCKER_USERNAME }}/flask-app:latest
            docker push ${{ secrets.DOCKER_USERNAME }}/flask-app:latest